# Generated by Django 2.2.5 on 2019-09-10 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.TextField()),
                ('vehicle_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_done', models.TextField(blank=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajn_site.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_f_name', models.TextField(max_length=20)),
                ('client_l_name', models.TextField(max_length=20)),
                ('client_email', models.TextField(blank=True)),
                ('mailing_address', models.TextField()),
                ('postal_code', models.TextField(max_length=7)),
                ('city', models.TextField(max_length=25)),
                ('vehicles', models.ManyToManyField(blank=True, to='cajn_site.Vehicle')),
            ],
        ),
    ]
