# Generated by Django 3.0 on 2019-12-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajn_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_work',
            name='last_service_date',
            field=models.DateField(blank=True),
        ),
    ]
