# Generated by Django 2.2.5 on 2019-11-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajn_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.TextField()),
                ('part_serial', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicle_work',
            name='last_service_hours',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_work',
            name='parts_id',
            field=models.ManyToManyField(blank=True, to='cajn_site.Parts'),
        ),
    ]
