# Generated by Django 2.2.2 on 2019-07-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajn_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='vehicle_work_id',
        ),
        migrations.AddField(
            model_name='clients',
            name='vehicle_id',
            field=models.ManyToManyField(to='cajn_site.Vehicle'),
        ),
    ]
