# Generated by Django 2.2.2 on 2019-07-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajn_site', '0002_auto_20190710_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='vehicle_id',
            new_name='vehicles',
        ),
    ]
