# Generated by Django 2.2.5 on 2019-11-03 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cajn_site', '0002_auto_20191102_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_work',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cajn_site.Clients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_work',
            name='last_service_date',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
