# Generated by Django 3.0 on 2019-12-20 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cajn_site', '0002_auto_20191219_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_work',
            name='title',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
