# Generated by Django 3.0 on 2019-12-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajn_site', '0003_vehicle_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_work',
            name='title',
            field=models.TextField(),
        ),
    ]
